test: &default

  # Credentials for REST APIs
  client_id: AZdhZnGGnnnUIWgAo856S2eC1ckNHThh0ZlI76cTbnIA7t50mCpZBVfAyJ1EpbiWHaduMXBT_7E-byci
  client_secret: ENfQr9SaVDLbuNRbZufp6a26gMT2VxLtHMZYG6-veMhlkOpgDz5KF0YYSo0eJqhCJH9u2Kctigpde6dw

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: info@ondraw.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
